import os
import json
import random
import io
import requests
import time
import base64
import shutil
from flask import Blueprint, render_template, request, jsonify, send_from_directory, url_for, send_file

# --- IMPORT IMAGE ENGINE ---
from image_engine import ImageGenerator

# Blueprint Setup
gui_editor_bp = Blueprint('gui_editor', __name__)
CONFIG_FILE = 'config.json'

KNOWN_DIRS = [
    "layouts",
    "editor_backgrounds",
    "plex_backgrounds",
    "jellyfin_backgrounds",
    "trakt_backgrounds",
    "radarrsonarr_backgrounds",
    "tmdb_backgrounds",
    "plexfriend_backgrounds"
]

LAYOUTS_DIR = 'layouts'
if not os.path.exists(LAYOUTS_DIR):
    os.makedirs(LAYOUTS_DIR)

# --- CONFIGURATION LOGIC ---
def load_config():
    defaults = {
        "general": {"overwrite_existing": False},
        "jellyfin": {"url": "", "api_key": "", "user_id": "", "excluded_libraries": ""},
        "plex": {"url": "", "token": ""},
        "tmdb": {"api_key": "", "language": "de-DE"},
        "radarr": {"url": "", "api_key": ""},
        "sonarr": {"url": "", "api_key": ""},
        "jellyseerr": {"url": "", "api_key": ""},
        "trakt": {"api_key": "", "username": "", "listname": ""},
        "editor": {"resolution": "1080"}
    }

    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            try:
                loaded = json.load(f)
                for key, value in loaded.items():
                    if key in defaults and isinstance(defaults[key], dict) and isinstance(value, dict):
                        defaults[key].update(value)
                    else:
                        defaults[key] = value
            except:
                pass
    return defaults

def save_config(config_data):
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config_data, f, indent=4)

# --- API ROUTES ---
@gui_editor_bp.route('/api/proxy/image')
def proxy_image():
    """ Proxies an image URL to bypass CORS/CORB blocks. """
    url = request.args.get('url')
    if not url:
        return "Missing URL", 400
    try:
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"}
        resp = requests.get(url, headers=headers, stream=True, timeout=10)
        resp.raise_for_status()
        return send_file(
            io.BytesIO(resp.content),
            mimetype=resp.headers.get('Content-Type', 'image/jpeg')
        )
    except Exception as e:
        print(f"Proxy Error for {url}: {e}")
        return str(e), 500

# --- NEW: Server-Side Generation Example ---
@gui_editor_bp.route('/api/generate_preview_server', methods=['POST'])
def generate_preview_server():
    """
    Example of using the ImageEngine to generate an image server-side.
    This keeps the main file clean and logic isolated.
    """
    data = request.json
    
    # Initialize Engine (Loads fonts/backgrounds once)
    engine = ImageGenerator()
    
    # Simulate getting an image (in reality you'd download it from data['backdrop_url'])
    # For demo, we use the base background as a placeholder for artwork
    artwork = engine.base_bg 
    
    # 1. Create Canvas
    engine.create_canvas(artwork)
    
    # 2. Draw Elements (Dynamic Layout happens automatically inside)
    engine.draw_logo_or_title(title_text=data.get('title', 'No Title'))
    engine.draw_info_text(f"{data.get('year')} • {data.get('rating')}")
    engine.draw_summary(data.get('overview', ''))
    engine.draw_custom_text_and_provider_logo("Preview Generated by Engine", "jellyfinlogo.png")
    
    # 3. Return Image
    return send_file(engine.get_bytes(), mimetype='image/jpeg')


@gui_editor_bp.route('/api/media/random')
def get_random_media():
    config = load_config()
    jf = config.get('jellyfin', {})
    excluded_libs = jf.get('excluded_libraries', "")
    excluded_list = [x.strip() for x in excluded_libs.split(',') if x.strip()]
    
    if jf.get('url') and jf.get('api_key'):
        headers = {"X-Emby-Token": jf['api_key']}
        clean_url = jf['url'].rstrip('/')
        
        excluded_paths = []
        if excluded_list:
            try:
                r_libs = requests.get(f"{clean_url}/Library/VirtualFolders", headers=headers, timeout=5)
                if r_libs.status_code == 200:
                    libs = r_libs.json()
                    for lib in libs:
                        if lib.get('Name') in excluded_list:
                            excluded_paths.extend(lib.get('Locations', []))
            except Exception as e:
                print(f"Error fetching libraries: {e}")

        url = f"{clean_url}/Users/{jf['user_id']}/Items?Recursive=true&IncludeItemTypes=Movie,Series&ExcludeItemTypes=BoxSet&SortBy=Random&Limit=50&Fields=Type,Overview,Genres,CommunityRating,ProductionYear,RunTimeTicks,ImageTags,Path,ProviderIds"
        
        try:
            r = requests.get(url, headers=headers, timeout=5)
            r.raise_for_status()
            items = r.json().get('Items', [])
            
            valid_items = []
            for item in items:
                if item.get('Type') == 'BoxSet':
                    continue
                if excluded_paths and item.get('Path') and any(ex in item['Path'] for ex in excluded_paths):
                    continue
                valid_items.append(item)
            
            if valid_items:
                item = random.choice(valid_items)
                
                # Check for Logo availability
                has_logo = 'Logo' in item.get('ImageTags', {})
                logo_url = f"{clean_url}/Items/{item['Id']}/Images/Logo?api_key={jf['api_key']}" if has_logo else None

                # Convert Ticks to Runtime
                ticks = item.get('RunTimeTicks', 0)
                minutes = (ticks // 600000000) if ticks else 0
                h, m = divmod(minutes, 60)
                runtime_str = f"{h}h {m}min" if h > 0 else f"{m}min"

                return jsonify({
                    "title": item.get('Name'),
                    "year": item.get('ProductionYear', 'N/A'),
                    "rating": item.get('CommunityRating', 'N/A'),
                    "overview": item.get('Overview', ''),
                    "genres": ", ".join(item.get('Genres', [])),
                    "runtime": runtime_str,
                    "backdrop_url": f"{clean_url}/Items/{item['Id']}/Images/Backdrop?api_key={jf['api_key']}",
                    "logo_url": logo_url,
                    "imdb_id": item.get('ProviderIds', {}).get('Imdb'),
                    "source": "Jellyfin"
                })
        except Exception as e:
            print(f"DEBUG: Jellyfin Error: {e}")

    # Fallback Data
    mock_samples = [
        {"title": "Interstellar", "year": 2014, "rating": 8.7, "overview": "A team of explorers travel through a wormhole in space...", "backdrop_url": "https://image.tmdb.org/t/p/original/gEU2vRuvmER7pG97uCqb9hHbp22.jpg", "logo_url": None},
        {"title": "The Dark Knight", "year": 2008, "rating": 9.0, "overview": "When the menace known as the Joker wreaks havoc...", "backdrop_url": "https://image.tmdb.org/t/p/original/nMKdUUepR0At5Iu98TjPLuOwwvM.jpg", "logo_url": None}
    ]
    sample = random.choice(mock_samples)
    sample["source"] = "Demo Mode"
    return jsonify(sample)

@gui_editor_bp.route('/api/settings', methods=['POST'])
def update_settings():
    save_config(request.json)
    return jsonify({"status": "success"})

@gui_editor_bp.route('/api/layouts/list')
def list_layouts():
    layouts = []
    if os.path.exists(LAYOUTS_DIR):
        layouts = [f.replace('.json', '') for f in os.listdir(LAYOUTS_DIR) if f.endswith('.json')]
    return jsonify(sorted(layouts))

@gui_editor_bp.route('/api/layouts/save', methods=['POST'])
def save_layout():
    data = request.json
    name = data.get('name')
    layout = data.get('layout')
    if not name or not layout:
        return jsonify({"status": "error", "message": "Missing name or layout data"}), 400
    
    safe_name = "".join(c for c in name if c.isalnum() or c in " ._-").strip()
    if not safe_name: return jsonify({"status": "error", "message": "Invalid name"}), 400

    path = os.path.join(LAYOUTS_DIR, f"{safe_name}.json")
    with open(path, 'w') as f:
        json.dump(layout, f)
    return jsonify({"status": "success"})

@gui_editor_bp.route('/api/layouts/load/<name>')
def load_layout(name):
    safe_name = "".join(c for c in name if c.isalnum() or c in " ._-").strip()
    path = os.path.join(LAYOUTS_DIR, f"{safe_name}.json")
    if os.path.exists(path):
        with open(path, 'r') as f:
            return jsonify(json.load(f))
    return jsonify({"status": "error", "message": "Layout not found"}), 404

@gui_editor_bp.route('/api/layouts/delete/<name>', methods=['POST'])
def delete_layout(name):
    safe_name = "".join(c for c in name if c.isalnum() or c in " ._-").strip()
    if not safe_name:
        return jsonify({"status": "error", "message": "Invalid name"}), 400

    json_path = os.path.join(LAYOUTS_DIR, f"{safe_name}.json")
    img_dir_path = os.path.join(os.path.dirname(__file__), "editor_backgrounds", safe_name)

    try:
        if os.path.exists(json_path):
            os.remove(json_path)
        if os.path.exists(img_dir_path):
            shutil.rmtree(img_dir_path)
        return jsonify({"status": "success"})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

@gui_editor_bp.route('/api/save_image', methods=['POST'])
def save_editor_image():
    data = request.json
    image_data = data.get('image')
    metadata = data.get('metadata', {})
    layout_name = data.get('layout_name', 'Default')
    canvas_json = data.get('canvas_json')
    overwrite_filename = data.get('overwrite_filename')

    if not image_data:
        return jsonify({"status": "error", "message": "No image data"}), 400
    
    if ',' in image_data:
        image_data = image_data.split(',')[1]
    
    folder = "editor_backgrounds"
    base_path = os.path.dirname(os.path.abspath(__file__))
    
    safe_layout = "".join(c for c in layout_name if c.isalnum() or c in " ._-").strip()
    if not safe_layout: safe_layout = "Default"
    
    full_path = os.path.join(base_path, folder, safe_layout)
    
    if not os.path.exists(full_path):
        os.makedirs(full_path)
    
    if overwrite_filename:
        filename = overwrite_filename
    else:
        filename = f"custom_{int(time.time())}.jpg"
        
        if metadata and metadata.get('title'):
            safe_title = "".join(c for c in metadata['title'] if c.isalnum() or c in " ._-").strip()
            parts = [safe_title]
            if metadata.get('year') and str(metadata['year']) != 'N/A':
                parts.append(str(metadata['year']))
            if metadata.get('imdb_id'):
                parts.append(str(metadata['imdb_id']))
            
            filename = " - ".join(parts) + ".jpg"

    filepath = os.path.join(full_path, filename)
    
    try:
        with open(filepath, "wb") as f:
            f.write(base64.b64decode(image_data))
            
        # Save JSON data if provided
        if canvas_json:
            json_path = os.path.splitext(filepath)[0] + ".json"
            with open(json_path, "w") as f:
                json.dump(canvas_json, f)
                
        return jsonify({"status": "success", "filename": filename})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

@gui_editor_bp.route('/api/gallery/data/<folder>/<path:filename>')
def get_gallery_image_data(folder, filename):
    base_path = os.path.dirname(os.path.abspath(__file__))
    
    # Determine target directory (logic shared with get_gallery_image)
    target_dir = ""
    if folder.startswith("Layout: "):
        layout_name = folder.replace("Layout: ", "").strip()
        safe_layout = "".join(c for c in layout_name if c.isalnum() or c in " ._-").strip()
        target_dir = os.path.join(base_path, "editor_backgrounds", safe_layout)
    elif folder == "Editor (Unsorted)":
        target_dir = os.path.join(base_path, "editor_backgrounds")
    elif folder in KNOWN_DIRS:
        target_dir = os.path.join(base_path, folder)
    else:
        return jsonify({"status": "error", "message": "Invalid folder"}), 400

    json_filename = os.path.splitext(filename)[0] + ".json"
    json_path = os.path.join(target_dir, json_filename)
    
    if os.path.exists(json_path):
        with open(json_path, 'r') as f:
            return jsonify(json.load(f))
    
    return jsonify({"status": "error", "message": "No layout data found for this image"}), 404

@gui_editor_bp.route('/get_local_background')
def get_local_background():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    return send_from_directory(current_dir, 'background.jpg')

@gui_editor_bp.route('/editor')
def editor_index():
    config = load_config()
    data = {"title": "TV Background", "backdrop_url": url_for('gui_editor.get_local_background')}
    return render_template('editor.html', data=data, config=config)

@gui_editor_bp.route('/api/gallery/list')
def list_gallery_images():
    gallery = {}
    base_path = os.path.dirname(os.path.abspath(__file__))
    for folder in KNOWN_DIRS:
        folder_path = os.path.join(base_path, folder)
        if os.path.exists(folder_path):
            if folder == "editor_backgrounds":
                # Scan subdirectories for layouts
                try:
                    subdirs = [d for d in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, d))]
                    if not subdirs:
                        # Fallback for root files
                        images = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
                        if images: gallery["Editor (Unsorted)"] = sorted(images)
                    else:
                        for subdir in subdirs:
                            sub_path = os.path.join(folder_path, subdir)
                            images = [f for f in os.listdir(sub_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
                            if images: gallery[f"Layout: {subdir}"] = sorted(images)
                except: pass
            elif folder != "layouts":
                images = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
                if images:
                    gallery[folder] = sorted(images)
    return jsonify(gallery)

@gui_editor_bp.route('/api/gallery/image/<folder>/<path:filename>')
def get_gallery_image(folder, filename):
    base_path = os.path.dirname(os.path.abspath(__file__))
    
    # Handle Layout subfolders
    if folder.startswith("Layout: "):
        layout_name = folder.replace("Layout: ", "").strip()
        safe_layout = "".join(c for c in layout_name if c.isalnum() or c in " ._-").strip()
        return send_from_directory(os.path.join(base_path, "editor_backgrounds", safe_layout), filename)
    
    if folder == "Editor (Unsorted)":
        return send_from_directory(os.path.join(base_path, "editor_backgrounds"), filename)

    if folder not in KNOWN_DIRS:
        return "Invalid folder", 400
         
    return send_from_directory(os.path.join(base_path, folder), filename)

if __name__ == '__main__':
    from flask import Flask
    app = Flask(__name__)
    app.register_blueprint(gui_editor_bp)
    app.run(debug=True, port=5000)
